### ISSUE TITLE
Empty line in requirements.txt

### ISSUE THREAD

**Issue by windelbouwman** [labapart/cross_sysroot#5]
Hi!

Just wanted to let you know, this is very cool.

I ran into a series of issues when given this tool a go:

- an empty line in a `requirements.txt` file assumes you want to install `''`, which I did not. Maybe a good idea to filter out empty lines?
- When using a distrbution url, you have to include the trailing slash. Since I copied the distribution url straight from my sources.list file, I did not include the trailing slash. Maybe change this so that a trailing slash is not required?

Another idea I had was to specify all the command-line parameters into a single yaml file, something like this:

```yaml
distribution: ubuntu
distribution-url:  http://ports.ubuntu.com/ubuntu-ports
arch: arm64
packages:
- systemd
- opencv
```

It would also be helpful to list an example invocation of the cross compiler with the sysroot flag.

One last question:
How is this approach different / better than using debootstrap?
